create table ACT_BPS_SUBSTITUTES (
    USERNAME NVARCHAR2(255) not null,
    SUBSTITUTE NVARCHAR2(255) not null,
    TASK_LIST NVARCHAR2(1000),
    SUBSTITUTION_START TIMESTAMP(6) not null,
    SUBSTITUTION_END TIMESTAMP(6),
    ENABLED NUMBER(3) default 1,
    CREATED TIMESTAMP(6),
    UPDATED TIMESTAMP(6),
    TRANSITIVE_SUBSTITUTE NVARCHAR2(255),
    TENANT_ID INTEGER NOT NULL,
    primary key (USERNAME, TENANT_ID)
);