<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions
        targetNamespace="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803"
        xmlns="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <wsdl:import namespace="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803"
                 location="ws-humantask-leantask-api.wsdl"/>


    <wsdl:binding name="leantaskOperationsSOAP" type="leanTaskOperations">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="registerLeanTaskDefinition">
            <soap:operation
                    soapAction="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803/registerLeanTaskDefinition"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="illegalStateFault">
                <soap:fault use="literal" name="illegalStateFault"/>
            </wsdl:fault>
            <wsdl:fault name="illegalAccessFault">
                <soap:fault use="literal" name="illegalAccessFault"/>
            </wsdl:fault>
        </wsdl:operation>

        <wsdl:operation name="unregisterLeanTaskDefinition">
            <soap:operation
                    soapAction="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803/unregisterLeanTaskDefinition"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="illegalArgumentFault">
                <soap:fault use="literal" name="illegalArgumentFault"/>
            </wsdl:fault>
            <wsdl:fault name="illegalAccessFault">
                <soap:fault use="literal" name="illegalAccessFault"/>
            </wsdl:fault>
        </wsdl:operation>

        <wsdl:operation name="listLeanTaskDefinitions">
            <soap:operation
                    soapAction="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803/listLeanTaskDefinitions"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="illegalAccessFault">
                <soap:fault use="literal" name="illegalAccessFault"/>
            </wsdl:fault>
        </wsdl:operation>

        <wsdl:operation name="createLeanTask">
            <soap:operation
                    soapAction="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803/createLeanTask"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="illegalArgumentFault">
                <soap:fault use="literal" name="illegalArgumentFault"/>
            </wsdl:fault>
            <wsdl:fault name="illegalAccessFault">
                <soap:fault use="literal" name="illegalAccessFault"/>
            </wsdl:fault>
        </wsdl:operation>

        <wsdl:operation name="createLeanTaskAsync">
            <soap:operation
                    soapAction="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803/createLeanTaskAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="illegalArgumentFault">
                <soap:fault use="literal" name="illegalArgumentFault"/>
            </wsdl:fault>
            <wsdl:fault name="illegalAccessFault">
                <soap:fault use="literal" name="illegalAccessFault"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="LeanTaskService">
        <wsdl:port binding="leantaskOperationsSOAP" name="leantaskOperationsPort">
            <soap:address location="http://localhost:9763/services/LeanTaskService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
