<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions
        targetNamespace="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803"
        xmlns="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <wsdl:import namespace="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803"
                 location="ws-humantask-leantask-api.wsdl"/>


    <wsdl:binding name="leanTaskCallbackOperationsSOAP" type="leanTaskCallbackOperations">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="createLeanTaskAsyncCallback">
            <soap:operation
                    soapAction="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803/createLeanTaskAsyncCallback" />
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="LeanTaskCBService">
        <wsdl:port binding="leanTaskCallbackOperationsSOAP" name="leanTaskCallbackOperationsPort">
            <soap:address location="http://localhost:9763/services/LeanTaskCBService" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
