--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--    http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

--
-- BPEL Related SQL Scripts
--


TRUNCATE TABLE IF EXISTS ODE_SCHEMA_VERSION;

--
--
--
TRUNCATE TABLE IF EXISTS ODE_JOB;

TRUNCATE TABLE IF EXISTS TASK_ATTACHMENT;
TRUNCATE TABLE IF EXISTS ODE_ACTIVITY_RECOVERY;
TRUNCATE TABLE IF EXISTS ODE_CORRELATION_SET;
TRUNCATE TABLE IF EXISTS ODE_CORRELATOR;
TRUNCATE TABLE IF EXISTS ODE_CORSET_PROP;
TRUNCATE TABLE IF EXISTS ODE_EVENT;
TRUNCATE TABLE IF EXISTS ODE_FAULT;
TRUNCATE TABLE IF EXISTS ODE_MESSAGE;
TRUNCATE TABLE IF EXISTS ODE_MESSAGE_EXCHANGE;
TRUNCATE TABLE IF EXISTS ODE_MESSAGE_ROUTE;
TRUNCATE TABLE IF EXISTS ODE_MEX_PROP;
TRUNCATE TABLE IF EXISTS ODE_PARTNER_LINK;
TRUNCATE TABLE IF EXISTS ODE_PROCESS;
TRUNCATE TABLE IF EXISTS ODE_PROCESS_INSTANCE;
TRUNCATE TABLE IF EXISTS ODE_SCOPE;
TRUNCATE TABLE IF EXISTS ODE_XML_DATA;
TRUNCATE TABLE IF EXISTS ODE_XML_DATA_PROP;
TRUNCATE TABLE IF EXISTS OPENJPA_SEQUENCE_TABLE;
TRUNCATE TABLE IF EXISTS STORE_DU;
TRUNCATE TABLE IF EXISTS STORE_PROCESS;
TRUNCATE TABLE IF EXISTS STORE_PROCESS_PROP;
TRUNCATE TABLE IF EXISTS STORE_PROC_TO_PROP;
TRUNCATE TABLE IF EXISTS STORE_VERSIONS;

--
-- Human Task Related SQL Scripts
--


TRUNCATE TABLE IF EXISTS HT_DEADLINE;
TRUNCATE TABLE IF EXISTS HT_DEPLOYMENT_UNIT;
TRUNCATE TABLE IF EXISTS HT_EVENT;
TRUNCATE TABLE IF EXISTS HT_GENERIC_HUMAN_ROLE;
TRUNCATE TABLE IF EXISTS HT_HUMANROLE_ORGENTITY;
TRUNCATE TABLE IF EXISTS HT_JOB;
TRUNCATE TABLE IF EXISTS HT_MESSAGE;
TRUNCATE TABLE IF EXISTS HT_ORG_ENTITY;
TRUNCATE TABLE IF EXISTS HT_PRESENTATION_ELEMENT;
TRUNCATE TABLE IF EXISTS HT_PRESENTATION_PARAM;
TRUNCATE TABLE IF EXISTS HT_TASK;
TRUNCATE TABLE IF EXISTS HT_TASK_ATTACHMENT;
TRUNCATE TABLE IF EXISTS HT_TASK_COMMENT;
TRUNCATE TABLE IF EXISTS HT_VERSIONS;
--
-- Attachment Management Related SQL Scripts
--
TRUNCATE TABLE IF EXISTS ATTACHMENT;


--
-- B4P Related SQL Scripts
--
TRUNCATE TABLE IF EXISTS HT_COORDINATION_DATA;
