--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--    http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

--
-- BPEL Related SQL Scripts
--


DROP TABLE IF EXISTS ODE_SCHEMA_VERSION;

--
--
--
DROP TABLE IF EXISTS ODE_JOB;

DROP TABLE IF EXISTS TASK_ATTACHMENT;
DROP TABLE IF EXISTS ODE_ACTIVITY_RECOVERY;
DROP TABLE IF EXISTS ODE_CORRELATION_SET;
DROP TABLE IF EXISTS ODE_CORRELATOR;
DROP TABLE IF EXISTS ODE_CORSET_PROP;
DROP TABLE IF EXISTS ODE_EVENT;
DROP TABLE IF EXISTS ODE_FAULT;
DROP TABLE IF EXISTS ODE_MESSAGE;
DROP TABLE IF EXISTS ODE_MESSAGE_EXCHANGE;
DROP TABLE IF EXISTS ODE_MESSAGE_ROUTE;
DROP TABLE IF EXISTS ODE_MEX_PROP;
DROP TABLE IF EXISTS ODE_PARTNER_LINK;
DROP TABLE IF EXISTS ODE_PROCESS;
DROP TABLE IF EXISTS ODE_PROCESS_INSTANCE;
DROP TABLE IF EXISTS ODE_SCOPE;
DROP TABLE IF EXISTS ODE_XML_DATA;
DROP TABLE IF EXISTS ODE_XML_DATA_PROP;
DROP TABLE IF EXISTS OPENJPA_SEQUENCE_TABLE;
DROP TABLE IF EXISTS STORE_DU;
DROP TABLE IF EXISTS STORE_PROCESS;
DROP TABLE IF EXISTS STORE_PROCESS_PROP;
DROP TABLE IF EXISTS STORE_PROC_TO_PROP;
DROP TABLE IF EXISTS STORE_VERSIONS;

--
-- Human Task Related SQL Scripts
--


DROP TABLE IF EXISTS HT_DEADLINE;
DROP TABLE IF EXISTS HT_DEPLOYMENT_UNIT;
DROP TABLE IF EXISTS HT_EVENT;
DROP TABLE IF EXISTS HT_GENERIC_HUMAN_ROLE;
DROP TABLE IF EXISTS HT_HUMANROLE_ORGENTITY;
DROP TABLE IF EXISTS HT_JOB;
DROP TABLE IF EXISTS HT_MESSAGE;
DROP TABLE IF EXISTS HT_ORG_ENTITY;
DROP TABLE IF EXISTS HT_PRESENTATION_ELEMENT;
DROP TABLE IF EXISTS HT_PRESENTATION_PARAM;
DROP TABLE IF EXISTS HT_TASK;
DROP TABLE IF EXISTS HT_TASK_ATTACHMENT;
DROP TABLE IF EXISTS HT_TASK_COMMENT;
DROP TABLE IF EXISTS HT_VERSIONS;
--
-- Attachment Management Related SQL Scripts
--
DROP TABLE IF EXISTS ATTACHMENT;


--
-- B4P Related SQL Scripts
--
DROP TABLE IF EXISTS HT_COORDINATION_DATA;